name:          Code Guide by Feed
description:   Standards for developing flexible, durable, and sustainable HTML, CSS and Javascript.
url:           http://mdo.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
